In [1]:
import pandas as pd
from openTSNE.tsne import TSNE
import numpy as np

In [2]:
import pickle

### Get the von Borries plot for a given dataset

In [3]:
hyperparameters_dict= {
    'n_components':2,
    'perplexity':100,  # default is 30
    'learning_rate':"auto",
    'early_exaggeration_iter':250,
    'early_exaggeration':"auto",
    'n_iter':2000,  # Default is 500
    'exaggeration':None,
    'dof':1,
    'theta':0.5,
    'n_interpolation_points':3,
    'min_num_intervals':50,
    'ints_in_interval':1,
    'initialization':"pca",
    'metric':"jaccard",  # deafult is euclidean
    'metric_params':None,
    'initial_momentum':0.8,
    'final_momentum':0.8,
    'max_grad_norm':None,
    'max_step_norm':5,
    'n_jobs':-1,
    'neighbors':"pynndescent",  # the default is auto
    'negative_gradient_method':"auto",
    'callbacks':None,
    'callbacks_every_iters':50,
    'random_state':None,
    'verbose':True,
    'random_state': 42,  
    }

In [4]:
von_borries_space = pd.read_csv("kerstin_fingerprints.csv")
np.array(von_borries_space)
X = np.array(von_borries_space).astype('bool')
# X = np.array(von_borries_space)
Xsmall = X[:6000]

In [5]:
Xsmall

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [ True, False, False, ..., False, False, False]],
      shape=(6000, 1024))

In [6]:
# load the training set
# von_borries_space = pd.read_csv("kerstin_fingerprints.csv")

# define the openTSNE object (kerstin hyperparameters)
# fp_array = np.array(fp_1024_only)

# tsne = TSNE(
#     perplexity=100,
#     n_iter=2000,
#     metric='jaccard',
#     random_state=42,
#     verbose=True,
# )

tsne = TSNE(**hyperparameters_dict)
# %time embedding_train = tsne.fit(np.array(von_borries_space))



# embedding_train = tsne.fit(np.array(von_borries_space))
embedding_train = tsne.fit(Xsmall)
# 
# 
#
# 
# train the openTSNE object



# Pickle it? 

--------------------------------------------------------------------------------
TSNE(early_exaggeration=12, metric='jaccard', n_iter=2000, n_jobs=-1,
     neighbors='pynndescent', perplexity=100, random_state=42, verbose=True)
--------------------------------------------------------------------------------


c:\Users\corderjo\switchdrive\pepper_sharing\.venv\Lib\site-packages\openTSNE\nearest_neighbors.py:436: UserWarning: `pynndescent` has recently changed which distance metrics are supported, and `openTSNE.nearest_neighbors` has not been updated. Please notify the developers of this change.
  warnings.warn(


===> Finding 300 nearest neighbors using NN descent approximate search using jaccard distance...


c:\Users\corderjo\switchdrive\pepper_sharing\.venv\Lib\site-packages\pynndescent\pynndescent_.py:939: UserWarning: Failed to correctly find n_neighbors for some samples. Results may be less than ideal. Try re-running with different parameters.
  warn(
c:\Users\corderjo\switchdrive\pepper_sharing\.venv\Lib\site-packages\openTSNE\nearest_neighbors.py:511: UserWarning: `pynndescent` failed to find neighbors for some of the points. As a workaround, openTSNE considers all such points similar to each other, so they will likely form a cluster in the embedding.The indices of the failed points are:
[ 583 3251 4169 4170 5001 5702 5704 5705 5706 5709 5710]
  warnings.warn(


   --> Time elapsed: 21.87 seconds
===> Calculating affinity matrix...
   --> Time elapsed: 8.92 seconds
===> Calculating PCA-based initialization...
   --> Time elapsed: 0.09 seconds
===> Running optimization with exaggeration=12.00, lr=500.00 for 250 iterations...
Iteration   50, KL divergence    nan, 50 iterations in 4.8121 sec
Iteration  100, KL divergence    nan, 50 iterations in 1.3528 sec
Iteration  150, KL divergence    nan, 50 iterations in 1.3507 sec
Iteration  200, KL divergence    nan, 50 iterations in 1.3951 sec
Iteration  250, KL divergence    nan, 50 iterations in 1.3812 sec
   --> Time elapsed: 10.29 seconds
===> Running optimization with exaggeration=1.00, lr=6000.00 for 2000 iterations...
Iteration   50, KL divergence    nan, 50 iterations in 1.3862 sec
Iteration  100, KL divergence    nan, 50 iterations in 1.4153 sec
Iteration  150, KL divergence    nan, 50 iterations in 1.4129 sec
Iteration  200, KL divergence    nan, 50 iterations in 1.4351 sec
Iteration  250, KL d

In [ ]:
von_borries_space 

In [ ]:
# Load the dataset of interest
target_space = pd.read_csv("mfps_WWTP_combined_data.tsv", sep="\t")
target_space_fingerprints = np.array(target_space .drop(columns='CanonicalSMILES'))

# Transform target dataset

# Array as Dataframe for plotting 

In [ ]:
target_space_fingerprints

array([[0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]], shape=(1156, 2048))

In [ ]:
pd.DataFrame(target_space_fingerprints[0], columns=['this_works'])

,this_works
0,0
1,1
2,0
3,0
4,0
...,...
2043,0
2044,0
2045,0
2046,0


In [ ]:
embedding_for_plot = pd.DataFrame()
embedding_for_plot['tsne_v1'] = embedding_test[:, 0]
embedding_for_plot['tsne_v2'] = embedding_test[:, 1]

'ls' is not recognized as an internal or external command,
operable program or batch file.


In [ ]:
# Retrain the openTSNE object with NIST data


# plot both

#### Envipath on von Borries

#### NIST on von Borries

##### Envipath on NIST

In [ ]:
# # Default hyperparameters for Kerstin's object

# n_components=2,
# perplexity=30,
# learning_rate="auto",
# early_exaggeration_iter=250,
# early_exaggeration="auto",
# n_iter=500,
# exaggeration=None,
# dof=1,
# theta=0.5,
# n_interpolation_points=3,
# min_num_intervals=50,
# ints_in_interval=1,
# initialization="pca",
# metric="euclidean",
# metric_params=None,
# initial_momentum=0.8,
# final_momentum=0.8,
# max_grad_norm=None,
# max_step_norm=5,
# n_jobs=1,
# neighbors="auto",
# negative_gradient_method="auto",
# callbacks=None,
# callbacks_every_iters=50,
# random_state=None,
# verbose=False


In [ ]:
### Training took 55 minutes in MacbookPro 3.5GHz
# # fp_array = np.array(fp_1024_only)
# 
# tsne = TSNE(
#     perplexity=100,
#     n_iter=2000,
#     metric='jaccard',
#     random_state=42,
#     verbose=True,
# )
# # %time embedding_train = tsne.fit(fp_array)
# # embedding_train = tsne.fit(fp_array)
# # transformed_embedding = embedding_train.transform(fp_array)
# # embedding_train = tsne.fit(fp_1024_only_boolean)
# # transformed_embedding = embedding_train.transform(fp_1024_only_boolean)
# # fit_transform_embedding_train = tsne.fit_transform(fp_1024_only_boolean)
# # embedding_train = tsne.fit(fp_1024_only_boolean)
# embedding_train = tsne.fit(fp_1024_only)

In [ ]:
# load the model from disk
filename = 'open_tsne_trained.sav'
loaded_embedding = pickle.load(open(filename, 'rb'))